variables:
  HTML_REPORT_SUBJECT:
    required: false
    type: string
    default:
    description: "Enter a custom report subject name."
  AUDIT_AWS_IAM_ALERT_LIST:
    required: false
    type: array
    default:
      - iam-unusediamgroup #
      - iam-multiple-keys #
      - iam-root-multiple-keys #
      - iam-inactive-key-no-rotation #
      - iam-active-key-no-rotation # cis_id:1.4
      - iam-missing-password-policy #
      - iam-passwordreuseprevention # cis_id:1.10
      - iam-expirepasswords # cis_id:1.11
      - iam-no-mfa #
      - iam-root-active-password #
      - iam-user-attached-policies # cis_id:1.16
      - iam-password-policy-uppercase # cis_id:1.05
      - iam-password-policy-lowercase # cis_id:1.06
      - iam-password-policy-symbol # cis_id:1.07
      - iam-password-policy-number # cis_id:1.08
      - iam-password-policy-min-length # cis_id:1.9
      - iam-cloudbleed-passwords-not-rotated #
      - iam-support-role # cis_id:1.22
      - iam-omnipotent-policy # cis_id 1.24
      - iam-user-password-not-used # not_violation
      - iam-unused-access # not_violation cis_id:1.3
      - iam-no-hardware-mfa-root # cis_id:1.14
      - iam-active-root-user # not_violation cis_id:1.1
      - iam-mfa-password-holders # not_violation cis_id:1.2
      - manual-ensure-security-questions # cis_id:1.15
      - manual-detailed-billing # cis_id:1.17
      - iam-root-key-access # cis_id:1.12
      - iam-root-no-mfa # cis_id:1.13
      - manual-strategic-iam-roles # cis_id:1.18
      - iam-initialization-access-key # cis_id:1.23
      - manual-contact-details # cis_id:1.19
      - manual-security-contact # cis_id:1.20
      - manual-resource-instance-access # cis_id:1.21
      - manual-full-privilege-user # cis_id:1.24
      - manual-appropriate-sns-subscribers # cis_id:3.15
      - manual-least-access-routing-tables # cis_id:4.5
      - manual-obscure-auth-info # meta_nist_171_id "3.5.11"
      - manual-least-access-routing-tables # cis_id:4.5
      - manual-maintenance-records #meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
      - manual-approved-monitored-maintenance # meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
      - manual-component-removal-approval #meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
    description: "Which rules would you like to run? Possible values are iam-inventory-users iam-inventory-roles iam-inventory-policies iam-inventory-groups iam-unusediamgroup iam-multiple-keys iam-root-multiple-keys iam-inactive-key-no-rotation iam-active-key-no-rotation iam-missing-password-policy iam-passwordreuseprevention iam-expirepasswords iam-no-mfa iam-root-active-password iam-user-attached-policies iam-password-policy-uppercase iam-password-policy-lowercase iam-password-policy-symbol iam-password-policy-number iam-password-policy-min-length iam-root-access-key-1 iam-root-access-key-2 iam-cloudbleed-passwords-not-rotated iam-support-role iam-user-password-not-used iam-unused-access iam-no-hardware-mfa-root iam-active-root-user iam-mfa-password-holders manual-ensure-security-questions manual-detailed-billing iam-root-key-access iam-root-no-mfa manual-strategic-iam-roles iam-initialization-access-key manual-contact-details manual-security-contact manual-resource-instance-access manual-full-privilege-user manual-appropriate-sns-subscribers manual-least-access-routing-tables iam-user-is-admin iam-instance-role-is-admin"
  AUDIT_AWS_IAM_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
    required: false
    type: string
    default:
  AUDIT_AWS_IAM_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is false."
    required: true
    type: string
    default: false
  AUDIT_AWS_IAM_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is change."
    required: true
    type: string
    default: "change"
  AUDIT_AWS_IAM_DAYS_PASSWORD_UNUSED:
    description: "Number of days for which password has not been used"
    required: true
    type: string
    default: "30"
  AUDIT_AWS_IAM_ACCOUNT_NUMBER:
    description: "The AWS account number. Required for a full CIS audit. This can be found by the root user at https://console.aws.amazon.com/billing/home?#/account"
    required: false
    type: string
    default:
  FILTERED_OBJECTS:
    description: "JSON object of string or regex of aws objects to include or exclude and tag in audit"
    required: false
    type: string
    default:
  AUDIT_AWS_IAM_S3_NOTIFICATION_BUCKET_NAME:
    required: false
    type: string
    default:
    description: "Enter S3 bucket name to upload reports. (Optional)"
  AUDIT_AWS_CIS_IAM_ADMIN_GROUP_PERMISSIONS:
    description: "This is a list of group permissions that signify an admin on the system. Used specifically for 3.1.1"
    required: true
    type: array
    default:
      - iam:PutGroupPolicy
      - iam:PutRolePolicy
      - iam:PutUserPolicy
      - iam:CreatePolicy
      - iam:CreatePolicyVersion
      - iam:AttachGroupPolicy
      - iam:AttachRolePolicy
      - iam:AttachUserPolicy
