variables: 
  AUDIT_AWS_IAM_ALERT_LIST:
    description: "Which alerts would you like to check for? (Default is all IAM alerts)"
    required: true
    type: array
    default:
      - iam-unusediamgroup
      - iam-inactive-key-no-rotation
      - iam-active-key-no-rotation
      - iam-passwordreuseprevention
      - iam-missing-password-policy
      - iam-expirepasswords
      - iam-no-mfa
      - iam-root-no-mfa
      - iam-root-active-key
      - iam-root-active-password
      - iam-user-attached-policies
  AUDIT_AWS_IAM_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
    required: true
    type: string
    default:
  AUDIT_AWS_IAM_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is false."
    required: true
    type: string
    default: false
  AUDIT_AWS_IAM_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is change."
    required: true
    type: string
    default: "change"
  AUDIT_AWS_IAM_ROLLUP_REPORT:
      description: "Would you like to send a Summary ELB report? Options - notify / nothing. Default is no / nothing."
      required: true
      type: string
      default: "nothing"
  AUDIT_AWS_IAM_HTML_REPORT:
      description: notify or nothing
      required: true
      type: string
      default: "notify"
