variables: 
  AUDIT_AWS_IAM_ALERT_LIST:
    description: "Which alerts would you like to check for? Default is all IAM alerts."
    required: true
    type: array
    default:
      - iam-unusediamgroup
      - iam-inactive-key-no-rotation
      - iam-active-key-no-rotation
      - iam-passwordreuseprevention
      - iam-missing-password-policy
      - iam-expirepasswords
      - iam-no-mfa
      - iam-root-no-mfa
      - iam-root-active-key
      - iam-root-active-password
      - iam-user-attached-policies
      - iam-password-policy-uppercase
      - iam-password-policy-lowercase
      - iam-password-policy-symbol
      - iam-password-policy-number
      - iam-password-policy-min-length
      - iam-root-access-key-1
      - iam-root-access-key-2
      - iam-inventory-users
      - iam-inventory-roles
      - iam-inventory-groups
      - iam-inventory-policies
  AUDIT_AWS_IAM_ALERT_RECIPIENT:
    description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
    required: false
    type: string
    default:
  AUDIT_AWS_IAM_ALLOW_EMPTY:
    description: "Would you like to receive empty reports? Options - true / false. Default is false."
    required: true
    type: string
    default: false
  AUDIT_AWS_IAM_SEND_ON:
    description: "Send reports always or only when there is a change? Options - always / change. Default is change."
    required: true
    type: string
    default: "change"
  AUDIT_AWS_IAM_ROLLUP_REPORT:
      description: "Would you like to send a rollup IAM report? This is a short email that summarizes the number of checks performed and the number of violations found. Options - notify / nothing. Default is nothing."
      required: true
      type: string
      default: "nothing"
  AUDIT_AWS_IAM_HTML_REPORT:
      description: "Would you like to send a full IAM report? This is an email that details any violations found and includes a list of the violating cloud objects. Options - notify / nothing. Default is nothing."
      required: true
      type: string
      default: "nothing"
  AUDIT_AWS_IAM_OWNER_TAG:
      description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
      required: false
      type: string
      default: "NOT_A_TAG"
